name: rehearse_app
description: Android application for rehearsing and curating notes.
publish_to: 'none'
version: 0.0.3

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  accordion: ^2.6.0
  provider: ^6.1.1
  page_transition: ^2.1.0
  sqflite: ^2.3.0
  sqflite_common_ffi: any
  path: ^1.8.3
  firebase_core: ^2.24.2
  cloud_firestore: any
  firebase_auth: any
  font_awesome_flutter: ^10.6.0
  google_sign_in: ^6.1.6
  multi_dropdown: ^2.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true