name: rehearse_app
description: Android application for rehearsing and curating notes.
publish_to: 'none'
version: 0.7.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  accordion: ^2.6.0
  provider: ^6.1.1
  sqflite: ^2.3.0
  path: ^1.8.3
  firebase_core: ^2.24.2
  cloud_firestore: any
  firebase_auth: any
  font_awesome_flutter: ^10.6.0
  google_sign_in: ^6.1.6
  multi_dropdown: ^2.1.2
  flutter_timezone: ^1.0.8
  flutter_local_notifications: ^16.3.0
  rxdart: ^0.27.7
  timezone: ^0.9.2
  google_mlkit_text_recognition: ^0.11.0
  camera: ^0.10.5+9
  flex_color_picker: ^3.3.1
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true