name: rehearse_app
description: Android application for rehearsing and curating notes.
publish_to: 'none'
version: 0.0.3

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  accordion: ^2.6.0
  provider: ^6.1.1
  page_transition: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true