// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApEPSRVEt8uKqZgR5lNK7EaKrz0jVF4Ho',
    appId: '1:941083888355:web:d062ec3583b51abc8813d6',
    messagingSenderId: '941083888355',
    projectId: 'rehearseapp-d9c43',
    authDomain: 'rehearseapp-d9c43.firebaseapp.com',
    storageBucket: 'rehearseapp-d9c43.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZNR4FaRNrVBVMj0FGXPKmvnMga2zc2Mo',
    appId: '1:941083888355:android:2942b42a6c2d313d8813d6',
    messagingSenderId: '941083888355',
    projectId: 'rehearseapp-d9c43',
    storageBucket: 'rehearseapp-d9c43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpJSIFUSfWuxGPNXn5T7GiNlVko2TRtP8',
    appId: '1:941083888355:ios:a78d61e782997ef58813d6',
    messagingSenderId: '941083888355',
    projectId: 'rehearseapp-d9c43',
    storageBucket: 'rehearseapp-d9c43.appspot.com',
    iosBundleId: 'com.gelegenheit.rehearseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpJSIFUSfWuxGPNXn5T7GiNlVko2TRtP8',
    appId: '1:941083888355:ios:646748c7b65c7e928813d6',
    messagingSenderId: '941083888355',
    projectId: 'rehearseapp-d9c43',
    storageBucket: 'rehearseapp-d9c43.appspot.com',
    iosBundleId: 'com.example.rehearseApp.RunnerTests',
  );
}
